# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 이승행
title: 빅데이터학과 이승행입니다.
email: tmdgodtmdgod@naver.com
# email_title:  (Email title override)
phone: 010-35xx-84xx 
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  seunghang


# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me(Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg.jpg)
about_content: | # this will include new lines to allow paragraphs
  <p>저는 빅데이터학과 17학번 이승행입니다. </p>
  <p>저는 서울 강북구에서 살고 있습니다. </p>
  <p>또한 서울 강북구에서 통학을 하고 있으며  </p>
  <p>유재석이 졸업한 용문고등학교를 졸업하고 </p>
  <p><mark>한림대학교</mark>에 재학중입니다. </p>
  <p>아직 부족하지만 <mark>노력</mark> 만큼은 가지고 임하고 있습니다.</p>
  
 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Escaping game
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: https://github.com/seunghang
        quote: >
           유니티 3D를 이용해 VR/AR 게임을 간단하게 만드는 중입니다.
        description: | # this will include new lines to allow paragraphs
          <p>1. 2층짜리 집을 Asset을 해와 집을 구성해놓습니다. </p>
          <p>2. 2층 집안에서 귀신이 랜덤으로 나옵니다.</p>
          <p>3. 귀신은 눈이 없고 소리로만 인식을 하고 저희를 찾습니다.</p>
          <p>4. 집안에 소모품을 이용해 소리를 조작하여 귀신을 헷갈리게 할 수 있습니다.</p> 
          <p>  아직 구현은 못했지만 이러한 구성을 이용해 제작할 생각입니다. </p>
          
          <p>  또한 이번 오픈소스 프로젝트때 간단하게 웹디자인을 해보려고 합니다.</p>
          <p>  자신은 없지만 제 수준에 맞게 노력해서 시도해보려고 합니다.</p>

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Hallym University
        sub_title: BigData
        caption: 2022
        quote: >
          <p>맨처음 17년도에 한림대학교에 입학하여 컴퓨터 공학과에 입학하였습니다. </p>
          <p>1학년때 너무 성급하게 놀기도 했고 학교생활을 못한게 후회되서 </p>
          <p>2학년에 군입대를 하여 20년도에 제대하고 롯데리아에서 알바를 좀하다가 21년도부터 다시 재학중입니다. </p>
          <p>이제와서 학점을 복구하고 있긴 하지만 대회나 학교경험이 없어서 조금 아쉽습니다. </p>
          <p>이번에 VR/AR 3D 강의를 들으면서 흥미가 생겨 아마 잘맞으면 이쪽으로 몰두해보려고 합니다 <p>
        description: | # this will include new lines to allow paragraphs
          부족하지만 최대한 열심히 해보겠습니다.!
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
        <h3><li>음악듣는 것을 좋아합니다.</li></h3>
        <center><p>주로 볼빨간사춘기나 아이유 노래를 좋아합니다</p></center>
        
        <h3><li>게임하는 것을 좋아합니다 </li></h3>
        <center><p>보통 리그오브레전드를 좋아하는데 제일 잘한다고 생각합니다.</p></center>
        
        <h3><li> 곱창을 좋아합니다 </li></h3>
        <center><p>음식중에 소곱창을 제일 좋아하지만 비싸서 자주는 못먹습니다.</p></center>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
